name: elevator-state-machine
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/epoberezkin/elevator-state-machine#readme
license: MIT
author: Evgeny Poberezkin
maintainer: evgeny@poberezkin.com
copyright: 2020 Evgeny Poberezkin
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - interact == 0.2.*
  - singletons == 2.6.*

executables:
  finite-state-machine-post:
    source-dirs: src
    main: Main.hs
